### ISSUE TITLE
Found a little bit of a problem

### ISSUE THREAD

**Issue by sunrishe** [DudarevDaniel/ConverterGenerator#11]
When two classes perform attribute copying, B inherits A, and A uses Lombok, and the attribute cannot be found.
I found a plugin [Converter](https://github.com/me10zyl/intellij-converter)(Quietly telling you that his plugin has many bugs. :)) with similar functionality, I hope I can help you.

```
import lombok.Data;

@Data
public class A {
    private String username;
    private String password;
    private String email;
}
```

```
import lombok.Data;

@Data
public class B extends A {
    public A convertAs(B from) {
        A to = new A();

        // Not mapped TO fields:
        // username
        // password
        // email
        return to;
    }
}
```

**Comment by sunrishe** [comment]
Just discovered that the problem is caused by extends, not related to Lombok.

**Comment by DudarevDaniel** [comment]
Yes, the plugin supports Lombok, but I disabled conversion of parent's fields. Will add this feature in next update. Thank you for the feedback.

**Comment by DudarevDaniel** [comment]
Submitted a new version with 'Use inherited fields' checkbox. Will be available as soon, as JetBrains approve it.
